# Generated by Django 3.0.3 on 2020-07-06 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('nearest_access', mapbox_location_field.models.LocationField(map_attrs={})),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Categories')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('is_fraudlent', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(default='Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Locations')),
                ('visitor', models.ForeignKey(default='Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
