# Generated by Django 3.0.3 on 2020-07-10 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 13, 12, 7, 821029)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 13, 12, 7, 821898)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 13, 12, 7, 823143)),
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 7, 10, 13, 12, 7, 821388))),
                ('category', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Categories')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.AddField(
            model_name='locations',
            name='sub_categories',
            field=models.ManyToManyField(to='main.SubCategories'),
        ),
    ]
