# Generated by Django 3.0.3 on 2020-07-10 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200710_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='icon',
            field=models.ImageField(default='static/main/img/favicon.png', upload_to='static/main/img/sub_cat_icons/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 20, 56, 13, 462283)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 20, 56, 13, 463323)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 20, 56, 13, 462686)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 20, 56, 13, 464437)),
        ),
    ]
