# Generated by Django 3.0.3 on 2020-07-21 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200713_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='locations',
            name='primary_sub_category',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.SubCategories'),
        ),
        migrations.AddField(
            model_name='locations',
            name='secondary_sub_categories',
            field=models.ManyToManyField(related_name='secondary_sub_categories', to='main.SubCategories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 15, 11, 21, 346098)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 15, 11, 21, 347141)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 15, 11, 21, 346493)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='icon',
            field=models.ImageField(default='main/img/sub_cat_icons/favicon.png', upload_to='main/img/sub_cat_icons/'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 15, 11, 21, 348409)),
        ),
    ]
