# Generated by Django 3.0.3 on 2020-07-22 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200722_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 20, 29, 52, 314705)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 20, 29, 52, 315747)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 20, 29, 52, 315143)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='icon',
            field=models.FileField(default='main/img/sub_cat_icons/favicon.png', upload_to='main/img/sub_cat_icons/'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='photo',
            field=models.ImageField(upload_to='main/photos/'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 20, 29, 52, 317131)),
        ),
    ]
