# Generated by Django 3.0.3 on 2020-07-27 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200727_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 15, 47, 597634)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locations',
            name='nearest_access',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 15, 47, 598674)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 15, 47, 598069)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 15, 47, 600161)),
        ),
    ]
