# Generated by Django 3.0.3 on 2020-07-28 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200727_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 8, 17, 254605)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='photo',
            field=models.FileField(upload_to='main/locations/photos/'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 8, 17, 255575)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 8, 17, 255020)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 8, 17, 257692)),
        ),
    ]
