# Generated by Django 3.0.3 on 2020-07-29 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200728_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 13, 50, 189361)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='photo',
            field=models.FileField(upload_to='main/locations/<django.db.models.fields.UUIDField>/'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 13, 50, 190309)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 13, 50, 189756)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='photo',
            field=models.ImageField(upload_to='main/locations/<django.db.models.fields.related.ForeignKey>/visits/'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 13, 50, 191556)),
        ),
    ]
