# Generated by Django 3.0.3 on 2020-07-29 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200729_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 18, 27, 23, 199980)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='photo',
            field=models.FileField(upload_to='main/locations/'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 18, 27, 23, 200922)),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 18, 27, 23, 200379)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='photo',
            field=models.ImageField(upload_to='main/locations/visits/'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 18, 27, 23, 202132)),
        ),
    ]
